[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = [
  "cd apps/backend",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd apps/backend",
  "python -c \"from email_classifier_llm.database import init_database; init_database()\""
]

[start]
cmd = "cd apps/backend && python deploy.py"