[phases.setup]
nixPkgs = ["python39", "pip", "postgresql"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r apps/backend/requirements.txt"
]

[start]
cmd = "python apps/backend/deploy.py"